# Generated by Django 4.0.4 on 2022-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ingreso', models.IntegerField()),
                ('fec_anuncio', models.DateTimeField()),
                ('decorador', models.CharField(max_length=1)),
                ('contador', models.IntegerField()),
                ('lugar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Contadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=5)),
                ('valor', models.IntegerField()),
                ('fec_ult_actual', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tramite', models.IntegerField()),
                ('contador', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('fec_ingreso', models.DateTimeField()),
                ('recibido', models.CharField(max_length=1)),
                ('atendido', models.CharField(max_length=1)),
                ('documento', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=1)),
                ('decorador', models.CharField(max_length=1)),
                ('lugar', models.CharField(max_length=20)),
            ],
        ),
    ]
