# Generated by Django 4.0.4 on 2022-07-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
