# Generated by Django 4.0.4 on 2022-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
