# Generated by Django 4.0.4 on 2022-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
