# Generated by Django 4.0.4 on 2022-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0005_clientes_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='activo',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='S', max_length=1),
        ),
    ]
