# Generated by Django 4.0.4 on 2022-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0007_alter_tramites_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='picture',
            field=models.ImageField(null=True, upload_to='statics/pictures/'),
        ),
    ]
