# Generated by Django 4.0.4 on 2022-08-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0014_clientes_fec_nac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncios',
            options={'ordering': ['-fec_anuncio']},
        ),
        migrations.AlterModelOptions(
            name='ingresos',
            options={'ordering': ['fec_ingreso']},
        ),
        migrations.AddField(
            model_name='ingresos',
            name='decorador',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tram_detalle',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
