# Generated by Django 4.0.4 on 2022-08-09 22:33

import admin_turnos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0015_alter_anuncios_options_alter_ingresos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=admin_turnos.models.UpperCaseCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombres',
            field=admin_turnos.models.UpperCaseCharField(max_length=50),
        ),
    ]
